# Generated by Django 3.2.5 on 2021-07-19 14:39

from django.db import migrations


def migrate_categories(apps, schema_editor):
    post = apps.get_model('posts', 'Post')
    post_category = apps.get_model('posts', 'PostCategory')
    for post in post.objects.all():
        if post.category_id:
            pc = post_category(
                post_id=post.id,
                category_id=post.category_id,
                is_main=True
            )
            pc.save()
            post.category_id = None
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210719_1435'),
    ]

    operations = [
        migrations.RunPython(
            migrate_categories,
            reverse_code=migrations.RunPython.noop
        )
    ]
